# This has the nodeselector category set for the provisioner
---
apiVersion: karpenter.sh/v1alpha5
kind: Provisioner
metadata:
  name: java
spec:
  labels:
    category: stage
  requirements:
    # - key: "node.kubernetes.io/instance-type" 
    #   operator: In
    #   values: [t2.small, t2.large, t2.xlarge, t2.2xlarge]
    - key: topology.kubernetes.io/zone
      operator: In
      values: [ap-southeast-1a, ap-southeast-1b, ap-southeast-1c] # Zones
    - key: karpenter.sh/capacity-type
      operator: In
      values: [spot]
  limits:
    resources:
      cpu: 1000
  provider:
    tags:
      category: stage
    instanceProfile: KarpenterNodeInstanceProfile-devops-toolkit
  ttlSecondsAfterEmpty: 30
